### ISSUE TITLE
Wordpress' Blacklist keys should be still usable 

### ISSUE THREAD

**Issue by giuliolastra** [WPDevelopers/disable-comments#143]
I've been using your plugin for a while and I've noticed that sometimes I need to edit **blacklist_keys** in `wp-admin/options-discussion.php`.
I need this field because plugins like **Contact Form 7** use this one to read banned keywords prevent spam on thieir forms.

How can I do? Could be a solution to make this textare always editable?

**Comment by abid112** [comment]
Hi @giuliolastra ,

Greetings.

In that case, you can uncheck Everywhere and select "**On Specific Post Type**" from Disable Comments settings page. You can select all post types there if you want to disable comments everywhere on your website.

After that, you will be able to navigate the **Discussion** page. 

Since **Discussion** page is part of the Comments so we disabled it when you choose "**Everywhere**".

Have a look at this video: https://d.pr/v/uGyuED

Hope it helps!
Thank you!

**Comment by giuliolastra** [comment]
That's great! Thanks!
